In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import requests
from IPython.display import display

In [2]:
url = "https://www.ebi.ac.uk/chembl/api/data/molecule/CHEMBL25.json"
response = requests.get(url)
print(response.status_code)

200

In [3]:
data=response.json()
type(data)

dict

In [4]:
data.keys()

dict_keys(['atc_classifications', 'availability_type', 'biotherapeutic', 'black_box_warning', 'chemical_probe', 'chirality', 'cross_references', 'dosed_ingredient', 'first_approval', 'first_in_class', 'helm_notation', 'inorganic_flag', 'max_phase', 'molecule_chembl_id', 'molecule_hierarchy', 'molecule_properties', 'molecule_structures', 'molecule_synonyms', 'molecule_type', 'natural_product', 'oral', 'orphan', 'parenteral', 'polymer_flag', 'pref_name', 'prodrug', 'structure_type', 'therapeutic_flag', 'topical', 'usan_stem', 'usan_stem_definition', 'usan_substem', 'usan_year', 'veterinary', 'withdrawn_flag'])

In [5]:
print(data["pref_name"])

ASPIRIN

In [6]:
properties = data["molecule_properties"]
print(properties)

{'alogp': '1.31', 'aromatic_rings': 1, 'full_molformula': 'C9H8O4', 'full_mwt': '180.16', 'hba': 3, 'hbd': 1, 'heavy_atoms': 13, 'mw_freebase': '180.16', 'np_likeness_score': '0.12', 'num_ro5_violations': 0, 'psa': '63.60', 'qed_weighted': '0.55', 'ro3_pass': 'N', 'rtb': 2}

In [7]:
df=pd.DataFrame([properties])
df.head()

,alogp,aromatic_rings,full_molformula,full_mwt,hba,hbd,heavy_atoms,mw_freebase,np_likeness_score,num_ro5_violations,psa,qed_weighted,ro3_pass,rtb
0,1.31,1,C9H8O4,180.16,3,1,13,180.16,0.12,0,63.60,0.55,N,2

In [8]:
print("Molecular weight : ",df['full_mwt'][0])
print("LogP : ",df['alogp'][0])
print("HBA : ",df['hba'][0])
print("HBD : ",df['hbd'][0])

Molecular weight :  180.16
LogP :  1.31
HBA :  3
HBD :  1

## Building the DrugInsightAI Dataset

In [9]:
url = ("https://www.ebi.ac.uk/chembl/api/data/activity.json"
      "?target_chembl_id=CHEMBL203"
      "&standard_type=IC50"
      "&limit=20")

response=requests.get(url)
print(response.status_code)

200

In [10]:
data=response.json()

In [11]:
type(data)

dict

In [12]:
data.keys()

dict_keys(['activities', 'page_meta'])

In [13]:
activities=data['activities']
activities[0]

{'action_type': None,
 'activity_comment': None,
 'activity_id': 32260,
 'activity_properties': [],
 'assay_chembl_id': 'CHEMBL674637',
 'assay_description': 'Inhibitory activity towards tyrosine phosphorylation for the epidermal growth factor-receptor kinase',
 'assay_type': 'B',
 'assay_variant_accession': None,
 'assay_variant_mutation': None,
 'bao_endpoint': 'BAO_0000190',
 'bao_format': 'BAO_0000357',
 'bao_label': 'single protein format',
 'canonical_smiles': 'Cc1cc(C)c(/C=C2\\C(=O)Nc3ncnc(Nc4ccc(F)c(Cl)c4)c32)[nH]1',
 'data_validity_comment': None,
 'data_validity_description': None,
 'document_chembl_id': 'CHEMBL1134862',
 'document_journal': 'Bioorg Med Chem Lett',
 'document_year': 2002,
 'ligand_efficiency': {'bei': '19.25',
  'le': '0.37',
  'lle': '2.94',
  'sei': '8.93'},
 'modality': None,
 'molecule_chembl_id': 'CHEMBL68920',
 'molecule_pref_name': None,
 'parent_molecule_chembl_id': 'CHEMBL68920',
 'pchembl_value': '7.39',
 'potential_duplicate': 0,
 'qudt_units': 'http://www.openphacts.org/units/Nanomolar',
 'record_id': 119482,
 'relation': '=',
 'src_id': 1,
 'standard_flag': 1,
 'standard_relation': '=',
 'standard_text_value': None,
 'standard_type': 'IC50',
 'standard_units': 'nM',
 'standard_upper_value': None,
 'standard_value': '41.0',
 'target_chembl_id': 'CHEMBL203',
 'target_organism': 'Homo sapiens',
 'target_pref_name': 'Epidermal growth factor receptor',
 'target_tax_id': '9606',
 'text_value': None,
 'toid': None,
 'type': 'IC50',
 'units': 'uM',
 'uo_units': 'UO_0000065',
 'upper_value': None,
 'value': '0.041'}

In [14]:
df=pd.DataFrame(activities)
df.head()

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,32260,[],CHEMBL674637,Inhibitory activity towards tyrosine phosphory...,B,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,uM,UO_0000065,None,0.041
1,None,None,32263,[],CHEMBL621151,Inhibition of autophosphorylation of human epi...,F,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,uM,UO_0000065,None,0.3
2,None,None,32265,[],CHEMBL615325,Inhibition of ligand-induced proliferation in ...,F,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,uM,UO_0000065,None,7.82
3,None,None,32267,[],CHEMBL674637,Inhibitory activity towards tyrosine phosphory...,B,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,uM,UO_0000065,None,0.17
4,None,None,32270,[],CHEMBL621151,Inhibition of autophosphorylation of human epi...,F,None,None,BAO_0000190,...,Homo sapiens,Epidermal growth factor receptor,9606,None,None,IC50,uM,UO_0000065,None,0.04

In [15]:
df.columns

Index(['action_type', 'activity_comment', 'activity_id', 'activity_properties',
       'assay_chembl_id', 'assay_description', 'assay_type',
       'assay_variant_accession', 'assay_variant_mutation', 'bao_endpoint',
       'bao_format', 'bao_label', 'canonical_smiles', 'data_validity_comment',
       'data_validity_description', 'document_chembl_id', 'document_journal',
       'document_year', 'ligand_efficiency', 'modality', 'molecule_chembl_id',
       'molecule_pref_name', 'parent_molecule_chembl_id', 'pchembl_value',
       'potential_duplicate', 'qudt_units', 'record_id', 'relation', 'src_id',
       'standard_flag', 'standard_relation', 'standard_text_value',
       'standard_type', 'standard_units', 'standard_upper_value',
       'standard_value', 'target_chembl_id', 'target_organism',
       'target_pref_name', 'target_tax_id', 'text_value', 'toid', 'type',
       'units', 'uo_units', 'upper_value', 'value'],
      dtype='object')

In [16]:
df=df[['molecule_chembl_id','target_chembl_id','standard_type','standard_value','standard_units']]
df.head()

,molecule_chembl_id,target_chembl_id,standard_type,standard_value,standard_units
0,CHEMBL68920,CHEMBL203,IC50,41.0,nM
1,CHEMBL68920,CHEMBL203,IC50,300.0,nM
2,CHEMBL68920,CHEMBL203,IC50,7820.0,nM
3,CHEMBL69960,CHEMBL203,IC50,170.0,nM
4,CHEMBL69960,CHEMBL203,IC50,40.0,nM

In [17]:
df.to_csv('../data/raw/egfr_activity.csv, index=False')